version: '3.8'

services:
  discovery-server:
    build:
      context: .
      dockerfile: Backend/discovery-server/Dockerfile.prod
    container_name: resify-discovery-server
    ports:
      - "8761:8761"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=
      - JVM_OPTS=-XX:ActiveProcessorCount=1 -XX:MaxRAMPercentage=40.0 -XX:+UseSerialGC -Xss256k -XX:MaxMetaspaceSize=128m
    deploy:
      resources:
        limits:
          memory: 400M
    networks:
      - resify-net
    restart: always

  gateway-service:
    build:
      context: .
      dockerfile: Backend/gateway-service/Dockerfile.prod
    container_name: resify-gateway-service
    ports:
      - "8080:8080"
    environment:
      - EUREKA_URI=http://discovery-server:8761/eureka/
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - RESUME_SERVICE_URI=https://resify-resume-service.onrender.com
      - CORS_ORIGINS=https://atsresify.me,https://www.atsresify.me
      - JVM_OPTS=-XX:ActiveProcessorCount=1 -XX:MaxRAMPercentage=40.0 -XX:+UseSerialGC -Xss256k -XX:MaxMetaspaceSize=128m
    deploy:
      resources:
        limits:
          memory: 400M
    depends_on:
      - discovery-server
    networks:
      - resify-net
    restart: always

  identity-service:
    build:
      context: .
      dockerfile: Backend/identity-service/Dockerfile.prod
    container_name: resify-identity-service
    ports:
      - "8081:8081"
    environment:
      - EUREKA_URI=http://discovery-server:8761/eureka/
      - DB_URL=${IDENTITY_DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
      - OAUTH_REDIRECT_URI=${OAUTH_REDIRECT_URI}
      - CORS_ORIGINS=https://atsresify.me,https://www.atsresify.me
      - JVM_OPTS=-XX:ActiveProcessorCount=1 -XX:MaxRAMPercentage=60.0 -XX:+UseSerialGC -Xss256k -XX:MaxMetaspaceSize=128m
    deploy:
      resources:
        limits:
          memory: 400M
    depends_on:
      - discovery-server
    networks:
      - resify-net
    restart: always

networks:
  resify-net:
    driver: bridge
    