version: '3.8'

services:
  intelligence-service:
    build:
      context: ./Backend
      dockerfile: intelligence-service/Dockerfile.prod
    container_name: resify-intelligence-service
    ports:
      - "8083:8083"
    environment:
      - EUREKA_URI=http://130.210.40.244:8761/eureka/
      - EUREKA_INSTANCE_IP_ADDRESS=92.4.84.21
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - DB_URL=${INTELLIGENCE_DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT:-5671}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
      - RABBITMQ_VIRTUAL_HOST=${RABBITMQ_VIRTUAL_HOST}
      - RABBITMQ_SSL_ENABLED=${RABBITMQ_SSL_ENABLED:-true}
      - JVM_OPTS=-XX:ActiveProcessorCount=1 -XX:MaxRAMPercentage=50.0 -XX:+UseSerialGC -Xss256k -XX:MaxMetaspaceSize=64m
    deploy:
      resources:
        limits:
          memory: 400M 
    networks:
      - resify-net
    restart: always

networks:
  resify-net:
    driver: bridge
